### PR TITLE
safe_core 0.9.0 integration

### PR DESCRIPTION
**Pull request by hitman401**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/safe_ffi/39)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/dns/add_service.rs, line 57 [r1]](https://reviewable.io:443/reviews/maidsafe/safe_ffi/39#-KCEZMUi3-FHZekfHLr8:-KCEZMUi3-FHZekfHLr9:498532620) ([raw file](https://github.com/maidsafe/safe_ffi/blob/4d3974ba3cf2820af2c4d67709de2fd8677ff305/src/dns/add_service.rs#L57)):_
trailing spaces

---

_[src/dns/register_dns.rs, line 67 [r1]](https://reviewable.io:443/reviews/maidsafe/safe_ffi/39#-KCEZAl05PpcFZZNI5Nv:-KCEZAl05PpcFZZNI5Nw:498532620) ([raw file](https://github.com/maidsafe/safe_ffi/blob/4d3974ba3cf2820af2c4d67709de2fd8677ff305/src/dns/register_dns.rs#L67)):_
trailing spaces

---

_[src/dns/register_public_id.rs, line 44 [r1]](https://reviewable.io:443/reviews/maidsafe/safe_ffi/39#-KCEZDqaqMTgPcrt-QVj:-KCEZDqaqMTgPcrt-QVk:498532620) ([raw file](https://github.com/maidsafe/safe_ffi/blob/4d3974ba3cf2820af2c4d67709de2fd8677ff305/src/dns/register_public_id.rs#L44)):_
trailing spaces

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_ffi/39)_

**Comment by hitman401** [comment]
_[src/dns/register_public_id.rs, line 44 [r1]](https://reviewable.io:443/reviews/maidsafe/safe_ffi/39#-KCEZDqaqMTgPcrt-QVj:-KCEaSZrx5B7S27UFvFw:-499146009) ([raw file](https://github.com/maidsafe/safe_ffi/blob/4d3974ba3cf2820af2c4d67709de2fd8677ff305/src/dns/register_public_id.rs#L44)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_ffi/39)_

**Comment by hitman401** [comment]
_[src/dns/register_dns.rs, line 67 [r1]](https://reviewable.io:443/reviews/maidsafe/safe_ffi/39#-KCEZAl05PpcFZZNI5Nv:-KCEaRhbOBS-CVKfj_57:-499146009) ([raw file](https://github.com/maidsafe/safe_ffi/blob/4d3974ba3cf2820af2c4d67709de2fd8677ff305/src/dns/register_dns.rs#L67)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_ffi/39)_

**Comment by hitman401** [comment]
_[src/dns/add_service.rs, line 57 [r1]](https://reviewable.io:443/reviews/maidsafe/safe_ffi/39#-KCEZMUi3-FHZekfHLr8:-KCEaNSM1T0Ty29wOapL:-499146009) ([raw file](https://github.com/maidsafe/safe_ffi/blob/4d3974ba3cf2820af2c4d67709de2fd8677ff305/src/dns/add_service.rs#L57)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_ffi/39)_

**Comment by ustulation** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_ffi/39)_

**Pull request merged**
