### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by afck**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_ffi/47)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @krishnaIndia (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by ustulation** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/lib.rs, line 604 [r2]](https://reviewable.io:443/reviews/maidsafe/safe_ffi/47#-KF8law50kYQGqIwuRz6:-KF8law50kYQGqIwuRz7:805374108) ([raw file](https://github.com/maidsafe/safe_ffi/blob/5bed43b01f1416cf201701d458c6a391c62c196c/src/lib.rs#L604)):_
Isnt 5 sec too long ? Or anything less and the result is unpredictable ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_ffi/47)_

**Comment by ustulation** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_ffi/47)_

**Pull request merged**
